### ISSUE TITLE
SparkSession.builder() not working

### ISSUE THREAD

**Issue by chriskryon** [Kotlin/kotlin-spark-api#114]
Hi, I'm trying to use the library, I put the dependency on the gradle.

The import worked, but the **Creating a SparkSession in Kotlin implementation** doesn't work, it gives an error in the builder, did I do something wrong?

![image](https://user-images.githubusercontent.com/42280549/148448978-981e6855-ae0c-477f-b940-caea4bab34e9.png)
![image](https://user-images.githubusercontent.com/42280549/148449298-96104ae9-e328-4a95-ab71-4e45bc11755a.png)

**Comment by Jolanrensen** [comment]
Hi there!
Do you still have this issue? 
We also support Spark 3.2 now, if you're interested: kotlin-spark-api-3.2:1.0.3

**Comment by Jolanrensen** [comment]
Closing this, feel free to reopen if you still face the bug
