### ISSUE TITLE
Documentation on how to use UDFs

### ISSUE THREAD

**Issue by vegarsti** [Kotlin/kotlin-spark-api#142]
Thanks for maintaining this project!

I would like to use the UDF functionality provided here. I'm, however, struggling with understanding how to use it. I think the `UDFWrapper`s are what I want.

Is there some code somewhere that uses these? I'd be happy to contribute with a PR with for example some tests, when I figure out how to use them.

**Comment by Jolanrensen** [comment]
An example inside https://github.com/JetBrains/kotlin-spark-api/tree/spark-3.2/examples/src/main/kotlin/org/jetbrains/kotlinx/spark/examples would still be valuable I think :) Thanks for letting us know!

**Comment by Jolanrensen** [comment]
Also look at UDAF https://spark.apache.org/docs/latest/sql-ref-functions-udf-aggregate.html

**Comment by Jolanrensen** [comment]
Added a complete new notation, support and examples for UDFs in https://github.com/Kotlin/kotlin-spark-api/pull/152. Will be present in the next update :)

https://github.com/Kotlin/kotlin-spark-api/tree/main#user-defined-functions
