### ISSUE TITLE
JavaCoverters for Scala data types can be replaced with CollectionConverters

### ISSUE THREAD

**Issue by Pihanya** [Kotlin/kotlin-spark-api#148]
https://github.com/JetBrains/kotlin-spark-api/blob/d62e3afe115c943bacd386fba28d0a13af660582/kotlin-spark-api/3.2/src/main/kotlin/org/jetbrains/kotlinx/spark/api/Conversions.kt#L28-L167

`JavaConverters` is partially deprecated in Scala 2.13.8:
https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/JavaConverters.scala#L78-L139

... so I suggest using methods from `scala.jdk.javaapi.CollectionConverters`.
I am attaching a file ([Conversions.kt.txt](https://github.com/JetBrains/kotlin-spark-api/files/8485570/Conversions.kt.txt)) that you can use to replace usage of deprecated methods with actual ones.

**Comment by asm0dey** [comment]
@Pihanya mind creating a PR?

**Comment by Jolanrensen** [comment]
Creating a scala-independent version of the conversions file at https://github.com/Kotlin/kotlin-spark-api/pull/175
uses JCP for the compatibility
