### ISSUE TITLE
Support user-defined types when generating schema

### ISSUE THREAD

**Issue by gschulze** [Kotlin/kotlin-spark-api#29]
Currently, the schema function in ApiV1.kt does not handle user-defined types correctly. If a field has a type with a UDT registration, the corresponding UserDefinedType should be used as schema.

I've drafted an implementation at [https://github.com/gschulze/kotlin-spark-api](https://github.com/gschulze/kotlin-spark-api). However, I'm not sure whether this is the right place to do it.

**Comment by asm0dey** [comment]
Thank you very much!

Could I please ask you to create minimalistic example with UDT for me to be able to test it?

**Comment by gschulze** [comment]
Hi, sorry for the late reply. I suggest waiting until both Support for Spark 2.4.x and 3.x has landed. I am happy to work on the issue once the structure has been finalized.

**Comment by asm0dey** [comment]
You'll be disappointed by new structure, but I don't have any idea on how to improve it yet :(

**Comment by gschulze** [comment]
I suggest using Maven profiles whenever possible to target different Spark/Scala versions. I'll try to come up with something and open a separate issue.

**Comment by asm0dey** [comment]
I thought about it, but there are some troubles: most important parts (scala code and kotlin code creating encoders and so on, not extensions) are different. Also, that's not possible (IIRC) to release from different profiles at same time.

**Comment by gschulze** [comment]
I filed a new ticket for building for specific environments, in particular Scala 2.11: https://github.com/JetBrains/kotlin-spark-api/issues/59

**Comment by asm0dey** [comment]
@gschulze with a couple of issues we already have working (and better!) implementation for both Spark 2.4 and Spark 3.0, so we can continue discussion on topic
