### ISSUE TITLE
Spark 2 support for arrays of complex objects

### ISSUE THREAD

**Issue by asm0dey** [Kotlin/kotlin-spark-api#64]
Currently test `should("handle arrays of generics")` is skipped on Spark 2 cause it fails. 

Arrays of generics may be useful when working with, for example, JSON data, where deeply nested arrays can be found.

Reproducer test: https://github.com/JetBrains/kotlin-spark-api/blob/21e4fdc4be9959782710c5185d9bf74f2dcb8998/kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt#L143-L151

**Comment by Jolanrensen** [comment]
Encoding something like `Pair<IntArray, Int>` also seems to fail on 2.4. It seems to not be able to handle complex objects with arrays as well.

**Comment by Jolanrensen** [comment]
Closing this since we don't support Spark 2 anyways anymore
